---
- name: AWS S3 Bucket List - Ansible
  hosts: all

  tasks:
  
    - name: List keys simple
      amazon.aws.s3_object:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        bucket: "{{ AWS_BUCKET }}"
        region: "{{ REGION }}"
        mode: list
        delegate_to: 127.0.0.1
      register: listresult
    
    - debug: msg={{listresult.s3_keys}}
