---
- name: chequea windows host ssh 
  hosts: all

  tasks:

    - name: test powershell
      ansible.windows.win_shell: get-host
      register: result_get_host
       
    - name: display result_get_host
      debug:
       var: result_get_host

    - name: "Download file from S3"
      ansible.windows.win_shell: "aws s3 sync s3://chilecompra-ansible-test/ C:\\Users\\cl170277171\\Desktop\\ansible_tmp\\
