---
- name: chequea windows host ssh 
  hosts: all

  tasks:

    - name: test powershell
      ansible.windows.win_shell: get-host
      register: result_get_host
       
    - name: display result_get_host
      debug:
       var: result_get_host

    - name: Copiar archivos a S3 usando AWS CLI
      command: aws s3 sync C:\Users\cl170277171\Desktop\ansible_tmp\ s3://chilecompra-ansible-test/
