---
- name: copy files web to aws s3
  hosts: localhost
 
  tasks:
  
    - name: Copiar archivos a AWS S3 con el módulo s3_object
      amazon.aws.s3_object:
        bucket: "{{ AWS_BUCKET }}"
        object: "{{ ITEM }}"
        src: "{{ FOLDER }}"
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: us-east-1
        mode: put
