---
- name: Copy a folder recursively where the source is on the remote host
  hosts: all
 
  tasks:
  
    - name: Copiar windows folder
      ansible.windows.win_copy:
        src: "{{ FOLDER }}"
        dest: "{{ FOLDER_TARGET }}"
        remote_src: true
