---
- name: Lista archivos de un folder
  hosts: all
 
  tasks:

    - name: Find hidden files in path
      ansible.windows.win_find:
        paths: "{{ FOLDER }}"
      register: apps_found

    - name: Get the content of found files from host
      slurp:
        src: "{{ item }}"
      loop: "{{ apps_found | json_query('files[].path') }}"
      register: slurped_files

    - name: Display result
      debug:
        msg: "Found application {{ item.item | win_dirname | win_basename }} with contents: {{ item.content | b64decode }}"
      loop: "{{ slurped_files.results }}"
