---
- name: Lista archivos de un folder
  hosts: all
 
  tasks:

    - name: Find hidden files in path
      ansible.windows.win_find:
        paths: "{{ FOLDER }}"
      register: wrapper

    - name: output wrapper
      debug:
        var: wrapper.files

    - name: output wrapper list
      debug:
        msg: "The file name is {{ item.path }}"
      with_items: "{{wrapper.files}}"
