# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
    - name: Obtain information about a folder
      ansible.windows.win_stat:
        path: C:\Temp
      register: folder_info
