# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
    - name: Copy a single file, but keep a backup
      ansible.windows.win_copy:
        src: /srv/myfiles/foo.conf
        dest: C:\Temp\renamed-foo.conf
        backup: yes
