# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
    - name: Example from an Ansible Playbook
      win_ping:

    - name: Induce an exception to see what happens
      win_ping:
        data: crash
