# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
    - name: Obtain information about a folder
      ansible.windows.win_stat:
        path: E:\eCommerce\eCommerce_WEBSite
      register: folder_info

    - name: Imprimir resultado
      debug: 
        var: folder_info.stat.exists

    - name: Subir archivos a AWS S3
      amazon.aws.s3_object:
        bucket: "{{ lookup('env', 'AWS_BUCKET') }}"
        object: "{{ item.path | regex_replace('\\\\', '/') | regex_replace('^.*/', '') }}"
        src: "{{ lookup('env', 'FOLDER') }}"
        region: us-east-1
      with_items: "{{ archivos_encontrados.files }}"
      vars:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
