# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: C:\Temp\foo.conf
      state: touch
