# Test connectivity to a windows host
# ansible winserver -m ansible.windows.win_ping
---
- name: Hello World!
  hosts: all
 
  tasks:
  
    - name: Obtain information about a folder
      ansible.windows.win_stat:
        path: E:\eCommerce\eCommerce_WEBSite
      register: folder_info

    - name: Imprimir resultado
      debug: 
        var: folder_info.stat.exists

    - name: Buscar archivos en la carpeta especificada
      win_find:
        paths: 'E:\eCommerce\eCommerce_WEBSite'
        recurse: yes
      register: archivos_encontrados

    - name: Mostrar lista de archivos
      debug:
        var: archivos_encontrados.files
