# List Keys S3 AWS
---
- name: Lista archivos de bucket S3
  hosts: localhost

  tasks:
  
    - name: List keys simple
      amazon.aws.s3_object:
        bucket: "{{ AWS_BUCKET }}"
        mode: list
      register: listresult
    
    - debug: msg={{listresult.s3_keys}}
