---
- name: AWS S3 Bucket List - Ansible
  hosts: localhost

  tasks:
  
    - name: List keys simple
      amazon.aws.s3_object:
        bucket: "{{ AWS_BUCKET }}"
        region: "{{ REGION }}"
        mode: list
      vars:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      register: listresult
    
    - debug: msg={{listresult.s3_keys}}
