---
- name: AWS S3 Bucket List - Ansible
  hosts: localhost

  tasks:
  
    - name: List keys simple
      amazon.aws.s3_object:
        bucket: "{{ AWS_BUCKET }}"
        mode: list
      register: listresult
    
    - debug: msg={{listresult.s3_keys}}
